Repository 01-ai/Yi, pull requests merged in 2024-01, with the labels that each got.

#283 [doc][improve] change relative path to absolute path
  README.md
Labels: documentation

#284 [doc][feat] add a quick start tutorial for using yi with llama.cpp
  README.md
  assets/img/yi_llama_cpp1.png
  assets/img/yi_llama_cpp2.png
  docs/yi_llama.cpp.md
Labels: documentation

#286 [doc][improve] change relative path to absolute path
  docs/yi_llama.cpp.md
Labels: documentation

#292 [doc][improve] change relative path to absolute path
  README.md
  docs/deployment.md
Labels: documentation

#291 Add LlamaEdge
  README.md
  docs/learning_hub.md
Labels: documentation

#305 [doc][feat] add quick start
  README.md
  assets/img/quick_start_path.png
  docs/deployment.md
  finetune/README.md
Labels: documentation

#310 [doc][feat] add web demo
  README.md
  assets/img/quick_start_path.png
  assets/img/yi_34b_chat_web_demo.gif
Labels: documentation

#332 [doc][trans] submit translation for Yi quick start - choose your path and Yi quick start - pip
  README_CN.md
Labels: translation

#333 [doc][trans] submit translation for Yi README: Benchmark + Who can use yi + Misc.
  README_CN.md
Labels: translation

#370 Update README.md
  README.md
Labels: doc
